#include "events.h"

ServerEvent serverEvents[] =
{
	{ true , SRV_ACCOUNT   , EVT_SERVER , "ACCT"  , "%s"                     },
	{ true , SRV_ADMIN     , EVT_CLIENT , "ADMN"  , "for %s"                 },
	{ true , SRV_AWAY      , EVT_CLIENT , "AWAY"  , "%s"                     },
	{ false, SRV_BURST     , EVT_SERVER , "BRST"  , "%s %ld %s"              },
	{ true , SRV_CREATE    , EVT_CLIENT , "CRT"   , "%s"                     },
	{ true , SRV_CLEARMODE , EVT_SERVER , "CLM"   , "%s"                     },
	{ true , SRV_KILL      , EVT_CLIENT , "KILL"  , "%s (%s)"                },
	{ true , SRV_DESTRUCT  , EVT_SERVER , "DSTR"  , "%s from %s"             },
	{ true , SRV_DESYNCH   , EVT_SERVER , "DSYN"  , "%s (%s)"                },
	{ false, SRV_EOBACK    , EVT_SERVER , "EBACK" , " "                      },
	{ false, SRV_EOB       , EVT_SERVER , "EBST"  , " "                      },
	{ false, SRV_ERROR     , EVT_SERVER , "ERROR" , "%s"                     },
	{ false, SRV_PING      , EVT_CLIENT , "PING"  , " "                      },
	{ true , SRV_GLINE     , EVT_SERVER , "GLINE" , "%s for %d seconds (%s)" },
	{ true , SRV_INVITE    , EVT_CLIENT , "INVT"  , "%s to %s"               },
	{ true , SRV_JOIN      , EVT_SERVER , "JOIN"  , "%s"                     },
	{ true , SRV_KICK      , EVT_CLIENT , "KICK"  , "%s from %s (%s) "       },
	{ true , SRV_JUPE      , EVT_SERVER , "JUPE"  , "%s"                     },
	{ true , SRV_LEAVE     , EVT_CLIENT , "PART"  , "%s"                     },
	{ true , SRV_UMODE     , EVT_CLIENT , "MODE"  , "%s for %s"              },
	{ false, SRV_CHMODE    , EVT_CLIENT , "MODE"  , "%s on %s"               },
	{ true , SRV_NICK      , EVT_SERVER , "NICK"  , "%s (%s@%s) (%s)"        },
	{ true , SRV_NICKCHG   , EVT_CLIENT , "NICK"  , "%s -> %s"               },
	{ true , SRV_QUIT      , EVT_CLIENT , "QUIT"  , "%s"                     },
	{ true , SRV_STATS     , EVT_SERVER , "STAT"  , "%c for %s"              },
	{ true , SRV_SERVER    , EVT_SERVER , "SERV"  , "%s"                     },
	{ true , SRV_SQUIT     , EVT_SERVER , "BREAK" , "%s"                     },
	{ true , SRV_TOPIC     , EVT_CLIENT , "TOPIC" , "on %s (%s)"             },
	{ false, SRV_SILENCE   , EVT_CLIENT , "SIL"   , ""                       },
	{ true , SRV_VERSION   , EVT_CLIENT , "VERS"  , "for %s"                 },
	{ true , SRV_WHOIS     , EVT_CLIENT , "WHOIS" , "%s to %s"               },
	{ true , SRV_WALLOPS   , EVT_CLIENT , "WALL"  , "%s"                     },
	{ true , SRV_WALLUSERS , EVT_CLIENT , "WALLU" , "%s"                     }
};

CommandEvent commandEvents[] =
{
	{ true , CMD_QUOTE        , "QUOTE"        , "%s" },
	{ true , CMD_DIE          , "DIE"          , " "  },
	{ true , CMD_DISABLE      , "DISABLE"      , "%s" },
	{ true , CMD_ENABLE       , "ENABLE"       , "%s" },
	{ true , CMD_RESTART      , "RESTART"      , " "  },
	{ true , CMD_CHLEVEL      , "CHLEVEL"      , "%s" },
	{ true , CMD_CHNAME       , "CHNAME"       , "%s" },
	{ true , CMD_SET          , "SET"          , "%s" },
	{ true , CMD_WRITE        , "WRITE"        , " "  },
	{ true , CMD_ADDUSER      , "ADDUSER"      , "%s" },
	{ true , CMD_MODUSER      , "MODUSER"      , "%s" },
	{ true , CMD_REMUSER      , "REMUSER"      , "%s" },
	{ true , CMD_BROADCAST    , "BROADCAST"    , "%s" },
	{ true , CMD_CLONE        , "CLONE"        , "%s" },
	{ true , CMD_CLONEACT     , "CLONEACT"     , "%s" },
	{ true , CMD_CLONEJOIN    , "CLONEJOIN"    , "%s" },
	{ true , CMD_CLONEPART    , "CLONEPART"    , "%s" },
	{ true , CMD_CLONEQUIT    , "CLONEQUIT"    , "%s" },
	{ true , CMD_CLONESAY     , "CLONESAY"     , "%s" },
	{ true , CMD_REOP         , "REOP"         , "%s" },
	{ true , CMD_SETTIME      , "SETTIME"      , " "  },
	{ true , CMD_JUPE         , "JUPE"         , "%s" },
	{ true , CMD_REFRESHG     , "REFRESHG"     , " "  },
	{ true , CMD_UNJUPE       , "UNJUPE"       , "%s" },
	{ true , CMD_CLEARCHAN    , "CLEARCHAN"    , "%s" },
	{ true , CMD_DEOPALL      , "DEOPALL"      , "%s" },
	{ true , CMD_DEVOICEALL   , "DEVOICEALL"   , "%s" },
	{ true , CMD_OPALL        , "OPALL"        , "%s" },
	{ true , CMD_VOICEALL     , "VOICEALL"     , "%s" },
	{ true , CMD_BAN          , "BAN"          , "%s" },
	{ true , CMD_GLINE        , "GLINE"        , "%s" },
	{ true , CMD_INVITE       , "INVITE"       , "%s" },
	{ true , CMD_MODE         , "MODE"         , "%s" },
	{ true , CMD_REMGLINE     , "REMGLINE"     , "%s" },
	{ true , CMD_UNBAN        , "UNBAN"        , "%s" },
	{ true , CMD_DEOP         , "DEOP"         , "%s" },
	{ true , CMD_DEVOICE      , "DEVOICE"      , "%s" },
	{ true , CMD_KICK         , "KICK"         , "%s" },
	{ true , CMD_OP           , "OP"           , "%s" },
	{ true , CMD_VOICE        , "VOICE"        , "%s" },
	{ true , CMD_CHANINFO     , "CHANINFO"     , "%s" },
	{ true , CMD_CHANLIST     , "CHANLIST"     , "%s" },
	{ true , CMD_HELP         , "HELP"         , "%s" },
	{ true , CMD_LOGIN        , "LOGIN"        , "%s" },
	{ true , CMD_LOGOUT       , "LOGOUT"       , " "  },
	{ true , CMD_MAP          , "MAP"          , " "  },
	{ true , CMD_OPERINFO     , "OPERINFO"     , "%s" },
	{ true , CMD_OPERMSG      , "OPERMSG"      , "%s" },
	{ true , CMD_SCAN         , "SCAN"         , "%s" },
	{ true , CMD_SERVINFO     , "SERVINFO"     , "%s" },
	{ true , CMD_SHOW         , "SHOW"         , "%s" },
	{ true , CMD_SHOWCOMMANDS , "SHOWCOMMANDS" , " "  },
	{ true , CMD_TRANSLATE    , "TRANSLATE"    , "%s" },
	{ true , CMD_UPTIME       , "UPTIME"       , " "  },
	{ true , CMD_WHOIS        , "WHOIS"        , "%s" },
	{ true , CMD_WHOISON      , "WHOISON"      , "%s" },
	{ true , CMD_CTCP_PING    , "[PING]"       , " "  },
	{ true , CMD_CTCP_VERSION , "[VERSION]"    , " "  },
	{ true , CMD_CTCP_GENDER  , "[GENDER]"     , " "  }
};

